### ISSUE TITLE
Address potential issues for users with cognitive disabilities

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y.github.io#14]
I didn't really think fully when writing the site copy about users with cognitive disabilities. We should probably do a review. Our content needs to be accessible on this front!

So we should review/remove:

  - Long or complex words/sentences if possible
  - Non-literal text such as sarcasm, metaphor or slang

@hollsk has helpfully written a [tone of voice guide and a plain english guide](http://pa11y.github.io/contributing/communications/#plain-english-guidelines) which should help in assessing the site content.

**Comment by hollsk** [comment]
I've just added a PR to remove one instance of metaphor. Reading the entire contributing/developers.md doc over in particular, there's a fair bit of slang in it, as well as the odd emoji. I think we need to decide how far we want to go with this, because the contributor guidelines don't say anything about this, and allow for chattier / more conversational style than straight accessibility guidelines would. 

The GDS guidelines for this are very good: https://www.gov.uk/guidance/content-design/writing-for-gov-uk (in particular see the "Writing to GOV.UK style" section)

**Comment by rowanmanning** [comment]
Yes deffo. I didn't really consider this stuff when I started writing the communications guide. I'm more than happy if we overhaul it. Maybe not _quite_ as complete a styleguide as gov.uk but along those lines

**Comment by hollsk** [comment]
I'm happy to open a separate PR for overhauling it, but tomorrow :-)

**Comment by hollsk** [comment]
I've merged my PR so we now have a tone of voice guide _and_ a plain english guide. Go us! 

@j-mes has helpfully offered to try to find some time to go through the docs to check for compliance.
