### ISSUE TITLE
Add a blog?

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y.github.io#70]
I'm starting to wonder whether we should have a blog which we just use to post information about new releases and stuff. With the Pa11y 5.0 beta I found myself wanting a place to put this stuff that isn't my personal one and is more permanent and easy to reference than a tweet.

I don't think it would really be used for "how to use Pa11y" style posts, our docs and the community are good at that. I'm thinking more like the [Node.js blog](https://nodejs.org/en/blog/).

What do people reckon?

**Comment by hollsk** [comment]
yes. we only didn't want a blog because we didn't want to have this extra thing to maintain, especially if it was just going to sit mostly empty because nobody has any time to write for it. That wouldn't be a problem with a similar format to the node.js blog. 

Right now we're using things like changelogs to do this work, but it lacks a way to unify information about the different tools, and a blog would really help with that.
